version: 2.1
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
          context: Docker Hub

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run: |
          TAG=$CIRCLE_SHA1
          DOCKER_REPO=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          docker build -t $DOCKER_REPO:$TAG .
          docker tag $DOCKER_REPO:$TAG $DOCKER_REPO:latest
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_REPO:$TAG
          docker push $DOCKER_REPO:latest
      - slack/status:
          webhook: ${DISCORD_WEBHOOK}

orbs:
  slack: circleci/slack@3.4.2
